language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - appcompat-v7:23.4.0
before_script: 
  - cd WAMap
script:
  - ./gradlew build connectedCheck
  
before_install:
  - android update sdk --filter extra-android-support --no-ui --force > /dev/null